### PR TITLE
Add seven wonders slide

### PR DESCRIPTION
**Pull request by harsitagarwalla187**

### CODE REVIEW

**Comment by harsitagarwalla187** [comment]
@sahilsingh7735 Unable to understand what checked failed.

**Comment by sahilsingh7735** [comment]
@harsitagarwalla187 you have to create a new branch, and then you have to raise a PR. 
And use bootstrap.

**Comment by harsitagarwalla187** [comment]
Do i have to make a PR again?

**Comment by harsitagarwalla187** [comment]
@sahilsingh7735 Why my this PR has been excluded from Hacktoberfest?

**Comment by sahilsingh7735** [comment]
@harsitagarwalla187 when I will merge it, then it will be excluded.

**Comment by sahilsingh7735** [comment]
@harsitagarwalla187 use bootstrap and rename web22.html as index.html.

**Comment by sahilsingh7735** [comment]
@harsitagarwalla187 use git pull command.

**Comment by harsitagarwalla187** [comment]
Should i make a new PR?

**Pull request merged**
