### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by ParthasarathiMahana**
Hi, I have added the Bootstrap view port in head, Currently that is what I can think of, if anything specific is needed please let me know.

### CODE REVIEW

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana use git pull and use bootstrap.

**Comment by ParthasarathiMahana** [comment]
@sahilsingh7735 please tell me how can I use bootstrap in the existing page, I have built.

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana just pull the existing code and bootstrap is already imported by someone... Just use bootstrap in your code .

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana can you just synchronize all the files and arrange it properly.

**Comment by ParthasarathiMahana** [comment]
@sahilsingh7735 synchronization done

**Pull request closed without merging**
