### PR TITLE
Seven wonders page is done.

### PR DESCRIPTION
**Pull request by ParthasarathiMahana**
Their are few things I would like to highlight, about what I did :

- [x] Added h1 tag with "seven wonders of world."
- [x] Created a style.css file where I have stored all the css class.
- [x] Added Images and Information about seven wonders in a simple manner.

Please have a look and let me know, Thank you @sahilsingh7735

### CODE REVIEW

**Comment by ParthasarathiMahana** [comment]
Hi, @sahilsingh7735 what is this error , and how can I resolve it.

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana now add bootstrap in this project. And make a branch then raise a PR ... Then only I will merge it..

**Comment by ParthasarathiMahana** [comment]
Ok, On it.

**Comment by ParthasarathiMahana** [comment]
hi, @sahilsingh7735  can you please review the changes and tell me what can be improved or is it ok?

**Pull request closed without merging**
