### PR TITLE
:sparkles: What to pack page done

### PR DESCRIPTION
**Pull request by aaushitiwari**
Signed-off-by: aaushitiwari <aaushitiwari01@gmail.com>

### CODE REVIEW

**Comment by aaushitiwari** [comment]
@sahilsingh7735, please take a look.

**Comment by sahilsingh7735** [comment]
@aaushitiwari can you make a branch and then raise PR.

**Comment by sahilsingh7735** [comment]
@aaushitiwari use git pull command and then raise PR.

**Comment by aaushitiwari** [comment]
Okay okay will do it asap

**Comment by sahilsingh7735** [comment]
@aaushitiwari link the pages to nav bar.

**Pull request merged**
