### PR TITLE
fixed  issue#37 which is to Convert HTML to react with react-router implementation.

### PR DESCRIPTION
**Pull request by parthivghose2919**
With an simple design on how to convert Html to react with react-router implementation...if any further changes required it will be done!!!

### CODE REVIEW

**Comment by parthivghose2919** [comment]
fixed issue #37  which is to Convert HTML to react with react-router implementation. ThankYou @sahilsingh7735

**Comment by sahilsingh7735** [comment]
@parthivghose2919  Can you add run scripts to the package.json , properly implement folder structure and
remove all html files and keep only .js files

**Comment by parthivghose2919** [comment]
Yaaa Sure @sahilsingh7735 I am trying to fix all the errors..ThankYou!!!

**Comment by sahilsingh7735** [comment]
@parthivghose2919 any update on this issue?

**Pull request closed without merging**
