### PR TITLE
DevBranch solves issue #14

### PR DESCRIPTION
**Pull request by Nincompup**

### CODE REVIEW

**Comment by Nincompup** [comment]
@sahilsingh7735  could u plzz tell me how to pass all checks ?

**Comment by sahilsingh7735** [comment]
@Nincompup make a separate CSS file and import it.

**Comment by Nincompup** [comment]
@sahilsingh7735  css file added

**Comment by sahilsingh7735** [comment]
@Nincompup use bootstrap and use git pull

**Pull request closed without merging**
